const SET_NAME_TEAM_ONE = "SET_NAME_TEAM_ONE";
const SET_NAME_TEAM_TWO = "SET_TEAM_TWO";
const SET_TIME_TIME = "SET_TIME_TIME";

const ADD_POINT_TEAM_ONE_FIRST = "ADD_POINT_TEAM_ONE_FIRST";
const REMOVE_POINT_TEAM_ONE_FIRST = "REMOVE_POINT_TEAM_ONE_FIRST";
const ADD_POINT_TEAM_ONE_SECOND = "ADD_POINT_TEAM_ONE_SECOND";
const REMOVE_POINT_TEAM_ONE_SECOND = "REMOVE_POINT_TEAM_ONE_SECOND";
const ADD_POINT_TEAM_ONE_THIRD = "ADD_POINT_TEAM_ONE_THIRD";
const REMOVE_POINT_TEAM_ONE_THIRD = "REMOVE_POINT_TEAM_ONE_THIRD";

const ADD_POINT_TEAM_TWO_FIRST = "ADD_POINT_TEAM_TWO_FIRST";
const REMOVE_POINT_TEAM_TWO_FIRST = "REMOVE_POINT_TEAM_TWO_FIRST";
const ADD_POINT_TEAM_TWO_SECOND = "ADD_POINT_TEAM_TWO_SECOND";
const REMOVE_POINT_TEAM_TWO_SECOND = "REMOVE_POINT_TEAM_TWO_SECOND";
const ADD_POINT_TEAM_TWO_THIRD = "ADD_POINT_TEAM_TWO_THIRD";
const REMOVE_POINT_TEAM_TWO_THIRD = "REMOVE_POINT_TEAM_TWO_THIRD";


export {
  SET_NAME_TEAM_ONE,
  SET_NAME_TEAM_TWO,
  SET_TIME_TIME,
  ADD_POINT_TEAM_ONE_FIRST,
  REMOVE_POINT_TEAM_ONE_FIRST,
  ADD_POINT_TEAM_TWO_FIRST,
  REMOVE_POINT_TEAM_TWO_FIRST,
  ADD_POINT_TEAM_ONE_SECOND,
  REMOVE_POINT_TEAM_ONE_SECOND,
  ADD_POINT_TEAM_ONE_THIRD,
  REMOVE_POINT_TEAM_ONE_THIRD,
  ADD_POINT_TEAM_TWO_SECOND,
  REMOVE_POINT_TEAM_TWO_SECOND,
  ADD_POINT_TEAM_TWO_THIRD,
  REMOVE_POINT_TEAM_TWO_THIRD
};
